### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 3. Shapes are [1] and [3]. 	From merging shape 0 with other shapes. for 'tower_0/lambda_1/concat/concat_dim' (op: 'Pack') with input shapes: [1], [3].

### ISSUE THREAD

**Issue by pontikos** [uw-biomedical-ml/irf-segmenter#4]
When I run:
```
pontikos@neuromancer:~/irf-segmenter$ python run.py example.png example-out.png
```

I get the following error:
```
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 3. Shapes are [1] and [3].
	From merging shape 0 with other shapes. for 'tower_0/lambda_1/concat/concat_dim' (op: 'Pack') with input shapes: [1], [3].
```
Full trace:
```
pontikos@neuromancer:~/irf-segmenter$ python run.py example.png example-out.png
Using TensorFlow backend.
2018-01-05 16:19:17.573040: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing Curl library
run.py:83: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same", activation="relu")`
  conv1 = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(inputs)
2018-01-05 16:19:18.840005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Found device 0 with properties: 
name: Quadro P6000 major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:02:00.0
totalMemory: 23.86GiB freeMemory: 23.20GiB
2018-01-05 16:19:18.840040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1300] Adding visible gpu device 0
2018-01-05 16:19:19.357810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:987] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 22451 MB memory) -> physical GPU (device: 0, name: Quadro P6000, pci bus id: 0000:02:00.0, compute capability: 6.1)
run.py:84: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same", activation="relu")`
  conv1 = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(conv1)
run.py:87: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same", activation="relu")`
  conv2 = Convolution2D(64, 3, 3, activation='relu', border_mode='same')(pool1)
run.py:88: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same", activation="relu")`
  conv2 = Convolution2D(64, 3, 3, activation='relu', border_mode='same')(conv2)
run.py:91: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), padding="same", activation="relu")`
  conv3 = Convolution2D(128, 3, 3, activation='relu', border_mode='same')(pool2)
run.py:92: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), padding="same", activation="relu")`
  conv3 = Convolution2D(128, 3, 3, activation='relu', border_mode='same')(conv3)
run.py:95: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), padding="same", activation="relu")`
  conv4 = Convolution2D(256, 3, 3, activation='relu', border_mode='same')(pool3)
run.py:96: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), padding="same", activation="relu")`
  conv4 = Convolution2D(256, 3, 3, activation='relu', border_mode='same')(conv4)
run.py:99: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), padding="same", activation="relu")`
  conv5 = Convolution2D(512, 3, 3, activation='relu', border_mode='same')(pool4)
run.py:100: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), padding="same", activation="relu")`
  conv5 = Convolution2D(512, 3, 3, activation='relu', border_mode='same')(conv5)
run.py:103: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  up6 = merge([UpSampling2D(size=(2, 2))(conv5), conv4], mode='concat', concat_axis=1)
/home/pontikos/.local/lib/python2.7/site-packages/keras/legacy/layers.py:458: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)
run.py:104: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), padding="same", activation="relu")`
  conv6 = Convolution2D(256, 3, 3, activation='relu', border_mode='same')(up6)
run.py:105: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), padding="same", activation="relu")`
  conv6 = Convolution2D(256, 3, 3, activation='relu', border_mode='same')(conv6)
run.py:107: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  up7 = merge([UpSampling2D(size=(2, 2))(conv6), conv3], mode='concat', concat_axis=1)
run.py:108: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), padding="same", activation="relu")`
  conv7 = Convolution2D(128, 3, 3, activation='relu', border_mode='same')(up7)
run.py:109: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), padding="same", activation="relu")`
  conv7 = Convolution2D(128, 3, 3, activation='relu', border_mode='same')(conv7)
run.py:111: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  up8 = merge([UpSampling2D(size=(2, 2))(conv7), conv2], mode='concat', concat_axis=1)
run.py:112: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same", activation="relu")`
  conv8 = Convolution2D(64, 3, 3, activation='relu', border_mode='same')(up8)
run.py:113: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same", activation="relu")`
  conv8 = Convolution2D(64, 3, 3, activation='relu', border_mode='same')(conv8)
run.py:115: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  up9 = merge([UpSampling2D(size=(2, 2))(conv8), conv1], mode='concat', concat_axis=1)
run.py:116: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same", activation="relu")`
  conv9 = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(up9)
run.py:117: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same", activation="relu")`
  conv9 = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(conv9)
run.py:119: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(1, (1, 1), activation="sigmoid")`
  conv10 = Convolution2D(1, 1, 1, activation='sigmoid')(conv9)
run.py:121: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Tensor("co..., inputs=Tensor("in...)`
  model = Model(input=inputs, output=conv10)
Traceback (most recent call last):
  File "run.py", line 126, in <module>
    model = make_parallel(model, 1)
  File "run.py", line 67, in make_parallel
    slice_n = Lambda(get_slice, output_shape=input_shape, arguments={'idx':i,'parts':gpu_count})(x)
  File "/home/pontikos/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/pontikos/.local/lib/python2.7/site-packages/keras/layers/core.py", line 651, in call
    return self.function(inputs, **arguments)
  File "run.py", line 51, in get_slice
    size = tf.concat(0, [ shape[:1] // parts, shape[1:] ])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1127, in concat
    dtype=dtypes.int32).get_shape().assert_is_compatible_with(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 923, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1013, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1001, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 964, in _autopacking_helper
    return gen_array_ops._pack(elems_as_tensors, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2929, in _pack
    "Pack", values=values, axis=axis, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3202, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 3. Shapes are [1] and [3].
	From merging shape 0 with other shapes. for 'tower_0/lambda_1/concat/concat_dim' (op: 'Pack') with input shapes: [1], [3].
pontikos@neuromancer:~/irf-segmenter$ python run.py example.png example-out.png
Using TensorFlow backend.
2018-01-05 16:24:35.425945: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing Curl library
run.py:83: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same", activation="relu")`
  conv1 = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(inputs)
2018-01-05 16:24:36.628737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Found device 0 with properties: 
name: Quadro P6000 major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:02:00.0
totalMemory: 23.86GiB freeMemory: 880.38MiB
2018-01-05 16:24:36.628765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1300] Adding visible gpu device 0
2018-01-05 16:24:37.310642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:987] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 535 MB memory) -> physical GPU (device: 0, name: Quadro P6000, pci bus id: 0000:02:00.0, compute capability: 6.1)
run.py:84: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same", activation="relu")`
  conv1 = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(conv1)
run.py:87: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same", activation="relu")`
  conv2 = Convolution2D(64, 3, 3, activation='relu', border_mode='same')(pool1)
run.py:88: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same", activation="relu")`
  conv2 = Convolution2D(64, 3, 3, activation='relu', border_mode='same')(conv2)
run.py:91: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), padding="same", activation="relu")`
  conv3 = Convolution2D(128, 3, 3, activation='relu', border_mode='same')(pool2)
run.py:92: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), padding="same", activation="relu")`
  conv3 = Convolution2D(128, 3, 3, activation='relu', border_mode='same')(conv3)
run.py:95: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), padding="same", activation="relu")`
  conv4 = Convolution2D(256, 3, 3, activation='relu', border_mode='same')(pool3)
run.py:96: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), padding="same", activation="relu")`
  conv4 = Convolution2D(256, 3, 3, activation='relu', border_mode='same')(conv4)
run.py:99: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), padding="same", activation="relu")`
  conv5 = Convolution2D(512, 3, 3, activation='relu', border_mode='same')(pool4)
run.py:100: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), padding="same", activation="relu")`
  conv5 = Convolution2D(512, 3, 3, activation='relu', border_mode='same')(conv5)
run.py:103: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  up6 = merge([UpSampling2D(size=(2, 2))(conv5), conv4], mode='concat', concat_axis=1)
/home/pontikos/.local/lib/python2.7/site-packages/keras/legacy/layers.py:458: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)
run.py:104: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), padding="same", activation="relu")`
  conv6 = Convolution2D(256, 3, 3, activation='relu', border_mode='same')(up6)
run.py:105: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), padding="same", activation="relu")`
  conv6 = Convolution2D(256, 3, 3, activation='relu', border_mode='same')(conv6)
run.py:107: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  up7 = merge([UpSampling2D(size=(2, 2))(conv6), conv3], mode='concat', concat_axis=1)
run.py:108: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), padding="same", activation="relu")`
  conv7 = Convolution2D(128, 3, 3, activation='relu', border_mode='same')(up7)
run.py:109: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), padding="same", activation="relu")`
  conv7 = Convolution2D(128, 3, 3, activation='relu', border_mode='same')(conv7)
run.py:111: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  up8 = merge([UpSampling2D(size=(2, 2))(conv7), conv2], mode='concat', concat_axis=1)
run.py:112: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same", activation="relu")`
  conv8 = Convolution2D(64, 3, 3, activation='relu', border_mode='same')(up8)
run.py:113: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same", activation="relu")`
  conv8 = Convolution2D(64, 3, 3, activation='relu', border_mode='same')(conv8)
run.py:115: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  up9 = merge([UpSampling2D(size=(2, 2))(conv8), conv1], mode='concat', concat_axis=1)
run.py:116: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same", activation="relu")`
  conv9 = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(up9)
run.py:117: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same", activation="relu")`
  conv9 = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(conv9)
run.py:119: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(1, (1, 1), activation="sigmoid")`
  conv10 = Convolution2D(1, 1, 1, activation='sigmoid')(conv9)
run.py:121: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Tensor("co..., inputs=Tensor("in...)`
  model = Model(input=inputs, output=conv10)
Traceback (most recent call last):
  File "run.py", line 126, in <module>
    model = make_parallel(model, 1)
  File "run.py", line 67, in make_parallel
    slice_n = Lambda(get_slice, output_shape=input_shape, arguments={'idx':i,'parts':gpu_count})(x)
  File "/home/pontikos/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/pontikos/.local/lib/python2.7/site-packages/keras/layers/core.py", line 651, in call
    return self.function(inputs, **arguments)
  File "run.py", line 51, in get_slice
    size = tf.concat(0, [ shape[:1] // parts, shape[1:] ])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1127, in concat
    dtype=dtypes.int32).get_shape().assert_is_compatible_with(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 923, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1013, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1001, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 964, in _autopacking_helper
    return gen_array_ops._pack(elems_as_tensors, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2929, in _pack
    "Pack", values=values, axis=axis, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3202, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 3. Shapes are [1] and [3].
	From merging shape 0 with other shapes. for 'tower_0/lambda_1/concat/concat_dim' (op: 'Pack') with input shapes: [1], [3].
```

**Comment by ayl** [comment]
Most likely happening due to color images and not grayscale input.

**Comment by pontikos** [comment]
Thanks!  This is what I see in the code when reading in the image:

```
>>> import cv2
>>> img=cv2.imread('example.png',cv2.IMREAD_GRAYSCALE)
>>> img
array([[  0,   8,  11, ..., 255, 255, 255],
       [255,  26,   0, ..., 255, 255, 255],
       [255,  15,   0, ..., 255, 255, 255],
       ..., 
       [255,   0,   0, ..., 255, 255, 255],
       [255,   0,   0, ..., 255, 255, 255],
       [255,   0,   0, ..., 255, 255, 255]], dtype=uint8)
>>> img.shape
(496, 768)
>>> img.ndim
2
```
Anything I can fix myself?

**Comment by ayl** [comment]
Can you check the TF and Keras versions that you have?

**Comment by pontikos** [comment]
>>> keras.__version__
'2.1.2'
>>> tensorflow.__version__
'1.5.0-rc0'

**Comment by ayl** [comment]
Need to use keras 1.2.1 and tf 0.12.1

**Comment by arokem** [comment]
Best way to use this is to create a new venv or conda env and use `pip install -r requirements.txt` to get all the requirements with the pinned versions.

**Comment by ayl** [comment]
Or use docker/nvidia-docker. Going to close this for now. Please open again if problems persist.

**Comment by pontikos** [comment]
Ok I'll give this a go using virtual env as I don't want to conflict with my current version of keras and tf.

May I suggest you add these instructions to the README as I see someone else had reported the same error in your closed issues :)

**Comment by ayl** [comment]
Added.
